### PR TITLE
fixes TORQUE_FINENESS related error messages

### LINKED ISSUE #22: Fix error message.
`Decrease TORQUE_UNIT` must be `Decrease TORQUE_FINENESS`.
https://github.com/openspur/yp-spur/blob/v1.15.0-rc4/src/param.c#L1288

### PR DESCRIPTION
**Pull request by at-wat**
This commit fixes #22.

### CODE REVIEW

File: src/param.c [hunk 1]
```diff
@@ -1282,10 +1283,10 @@ void set_param_velocity( void )
 			{
 				yprintf( OUTPUT_LV_PARAM, "Info: INERTIA_SELF[%d]: %d\n", j,
 						(int)(g_P[YP_PARAM_INERTIA_SELF][j] * ff) );
-				if( abs(g_P[YP_PARAM_INERTIA_SELF][j] * ff) < 5 )
+				if( abs(g_P[YP_PARAM_INERTIA_SELF][j] * ff) < 2 )
 				{
 					yprintf( OUTPUT_LV_ERROR, "ERROR: INERTIA_SELF[%d] too small\n", j );
```
Comment (at-wat) [inline src/param.c]: too small -> fixed point value underflow

File: src/param.c [hunk 2]
```diff
@@ -1126,6 +1126,7 @@ void set_param_motor( void )
 			if( ki == 0 )
```
Comment (at-wat) [inline src/param.c]: show ki

Comment (at-wat) [inline src/param.c]: Info: torque constant[i]:

File: src/param.c [hunk 3]
```diff
@@ -1126,6 +1126,7 @@ void set_param_motor( void )
...
 			{
 				yprintf( OUTPUT_LV_ERROR, "ERROR: TORQUE_FINENESS too small\n" );
```
Comment (at-wat) [inline src/param.c]: torque constant[i] fixed point value underflow
